name = "RepeaterPlacement"
uuid = "515e528d-8d63-45a6-94ad-38e69c682317"
authors = ["Guus Avis <guusavis@hotmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StochasticAD = "e4facb34-4f7e-4bec-b153-e122c37934ac"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DataStructures = "0.18.20"
GraphPlot = "0.6.0"
Graphs = "1.9.0"
JLD2 = "0.5.8"
Optimisers = "0.3.4, 0.4.1"
ParameterSchedulers = "0.4.2"
Plots = "1.40.8"
SimpleWeightedGraphs = "1.4.0"
StatsBase = "0.34.3"
StochasticAD = "0.1.26"
Statistics = "1.10.0"
